replicaCount: 2

image:
  repository: saishandilya/taxi-app
  tag: "1.0.1"
  pullPolicy: Always

imagePullSecrets:
  name: docker-config-creds
  dockerconfigjson: ""

service:
  type: LoadBalancer
  port: 8001
  targetPort: 8080

namespace: taxi-app
