apiVersion: v1
kind: Service
metadata:
  name: taxi-booking-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: taxi-booking
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}